### ISSUE TITLE
Unable to unpack any archive with jre-oracle image

### ISSUE THREAD

**Issue by fenque** [edannenberg/gentoo-bb#30]
071d363699c3 tmp # tar zxvf unzip60.tar.gz 
tar: short read

071d363699c3 tmp # unzip infozip_binaries_linux_x64.zip 
Archive:  infozip_binaries_linux_x64.zip
  inflating: zip
unzip: inflate error

**Comment by edannenberg** [comment]
Thanks for reporting. Apparently a regression with busybox. Maybe related to the recent switch to musl from uclibc. Gonna have a closer look at this next week.

**Comment by fenque** [comment]
Thanks!

**Comment by edannenberg** [comment]
In the meantime you can replace the busybox binaries by adding `app-arch/tar` and/or `app-arch/unzip` to `PACKAGES` in `Buildconfig.sh`, then just rebuild the image.

**Comment by edannenberg** [comment]
As suspected this was related to the recent musl switch, the Gentoo musl overlay is missing a unzip regression patch from the main overlay. I added a temp. workaround until it's fixed upstream.

Monthly image updates are gonna be a bit delayed this month due to man flu, should be on docker hub by the weekend though.

**Comment by edannenberg** [comment]
Busybox 1.24.2 is out and unzips as expected. Updated images are on Docker Hub. (20160317)
