### ISSUE TITLE
>=musl-1.1.15-r2 problems

### ISSUE THREAD

**Issue by soredake** [edannenberg/gentoo-bb#38]
```
!!! 'net-misc/openssh' (virtual/ssh) is part of your system profile.
!!! Unmerging it may be damaging to your system.


 net-misc/openssh
    selected: 7.3_p1-r6 
   protected: none 
     omitted: none 

All selected packages: =net-misc/openssh-7.3_p1-r6

>>> 'Selected' packages are slated for removal.
>>> 'Protected' and 'omitted' packages will not be removed.

>>> Waiting 5 seconds before starting...
>>> (Control-C to abort)...
>>> Unmerging in: 5 4 3 2 1
>>> Unmerging (1 of 1) net-misc/openssh-7.3_p1-r6...
 * suid/sgid file(s) with suspicious hardlink(s):
 * 
 *  /usr/lib64/misc/ssh-keysign
 * 
 * See the Gentoo Security Handbook guide for advice on how to proceed.
```

`rm /usr/lib64/misc/ssh-keysign` is needed before `emerge -C`

**Comment by edannenberg** [comment]
Thanks for reporting, fix should be in master by the weekend.

**Comment by edannenberg** [comment]
Hmm, I was not able to reproduce this, could you try again from a fresh state? If the issue still persists, what's your stage3 date?

**Comment by edannenberg** [comment]
Odd, build ran fine yesterday. Try checking the logs for some clues:

    docker ps -a
    docker cp <build-container-id>:/var/log/portage/cross-x86_64-pc-linux-musl-info.log ~/musl.log

**Comment by soredake** [comment]
https://transfer.sh/bQaMZ/musl.log
https://transfer.sh/S9u3t/musl.log.xz

**Comment by edannenberg** [comment]
A case of bad timing, couple hours after I did the rebuild last thursday `musl-1.1.15-r2` came out, which broke the build. Masked the build for now. Did a complete rebuild with stage 3 `20161020` today, looks good.

**Comment by soredake** [comment]
After this https://github.com/gentoo/gentoo/commit/78404f8f8ea9b5dde8d59e4fec442c090328ee65, we definitely need to do something,

**Comment by edannenberg** [comment]
Yep, I should have reported this upstream earlier. :(

https://bugs.gentoo.org/show_bug.cgi?id=605270

As a workaround you could restore the old `1.1.15` ebuild manually for now I guess.

**Comment by jbergstroem** [comment]
How about sidestepping this by not cross-compiling and using a [native musl stage3](http://distfiles.gentoo.org/experimental/amd64/musl/) as base instead? Will shake things up a bit, but its at least an alternative.

**Comment by edannenberg** [comment]
I fear this will be a bit more of a shake up. :p But it has been quite a while since I last tried that, things might be a lot smoother now. As a very quick workaround I removed a couple of lines in `Buildconfig.sh` and `Dockerfile.template` of busybox image to use default build container instead of musl. Nothing for production as the good old dns resolution bug in static glibc busybox is still alive, but enough for tinkering. Bug got confirmed on Gentoo's bugtracker and seems to get some interest, hopefully resolved soon.

For the future it would be nice if different Gentoo stage3 could be supported at the same time, i.e. have a standard stage3 and musl stage3 coexist, would remove the need for crosscompiling musl stuff while still leaving easy out's if musl is not an option.

**Comment by edannenberg** [comment]
@soredake I somewhat located the issue with `PACKAGES.md` generation. Only seems to happen when a new file is created, which apparently has the wrong permissions for the host user to add the final header. I fixed the issue in `feat/multistage3` branch, generated `rootfs.tar` files now also get proper host UID/GID ownership.

Still can't reproduce the `rm /usr/lib64/misc/ssh-keysign` bit.
