### ISSUE TITLE
rutorrent install error 

### ISSUE THREAD

**Issue by soredake** [edannenberg/gentoo-bb#41]
```
 * vhosts USE flag not set - auto-installing using webapp-config
 * This is an installation
 * rutorrent-3.7 is not installed - using install mode
 * Running /emerge-root/usr/sbin/webapp-config -h localhost -u root -d /rutorrent -I rutorrent 3.7
* Fatal error: Unable to determine location of master copy
* Fatal error(s) - aborting
```

**Comment by edannenberg** [comment]
Looks like one of those few packages that has trouble with a custom root. Try the approach outlined in #33, generate the binary package by installing it manually in `configure_bob` hook first. The `webapp-config` part most likely needs be run via Dockerfile to find nginx, if nginx is supported by `webapp-config` that is, haven't used it in ages. Might need to set the `vhosts` use flag to disable `webapp-config`.

**Comment by soredake** [comment]
With vhosts rutorrent is installed normally, but now php is erroring:
```
 * Messages for package dev-lang/php-5.6.26 merged to /emerge-root/:

 * FAILED postinst: 1
 * ERROR: dev-lang/php-5.6.26::gentoo failed (postinst phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line 115:  Called pkg_postinst
 *   environment, line 3332:  Called die
 * The specific snippet of code:
 *                   eselect php set $m php${SLOT} || die;
 * 
 * If you need support, post the output of `emerge --info '=dev-lang/php-5.6.26::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=dev-lang/php-5.6.26::gentoo'`.
 * The complete build log is located at '/var/tmp/portage/dev-lang/php-5.6.26/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-lang/php-5.6.26/temp/environment'.
 * Working directory: '/usr/lib64/python3.4/site-packages'
 * S: '/var/tmp/portage/dev-lang/php-5.6.26/work/php-5.6.26'
```

this code in ebuild causing this
```
	# Create the symlinks for php
	for m in ${SAPIS}; do
		[[ ${m} == 'embed' ]] && continue;
		if use $m ; then
			local ci=$(eselect php show $m)
			if [[ -z $ci ]]; then
				eselect php set $m php${SLOT} || die
				einfo "Switched ${m} to use php:${SLOT}"
				einfo
			elif [[ $ci != "php${SLOT}" ]] ; then
				elog "To switch $m to use php:${SLOT}, run"
				elog "    eselect php set $m php${SLOT}"
				elog
			fi
		fi
	done
```

**Comment by edannenberg** [comment]
Same deal, generate the binary package in the `configure_bob` hook first. You can take a look at the [nginx-php5.6](https://github.com/edannenberg/gentoo-bb/blob/master/dock/gentoobb/images/nginx-php5.6/Buildconfig.sh#L23) image for a full example. Then either create the symlink for the php binary manually or run `eselect` in the second build phase via `Dockerfile`.

**Comment by soredake** [comment]
php is fixed, now webapp-config can't find python
```
/emerge-root/usr/sbin/webapp-config: no supported Python implementation variant found!
 * ERROR: www-apps/rutorrent-3.7::junkdrawer failed (setup phase):
 *   Could not read settings from webapp-config!
 * 
 * Call stack:
 *     ebuild.sh, line  115:  Called pkg_setup
 *   environment, line 1984:  Called webapp_pkg_setup
 *   environment, line 2950:  Called webapp_read_config
 *   environment, line 3001:  Called die
 * The specific snippet of code:
 *           ENVVAR=$(${WEBAPP_CONFIG} --query ${PN} ${PVR}) || die "Could not read settings from webapp-config!";
 * 
```

**Comment by edannenberg** [comment]
Why bother? `webapp-config` just provides some config for the httpd, unless you have other reasons to have python in your docker image it's not worth the footprint, nor is there really a need to have `webapp-config` I'd wager. I'd just hit google for a rutorrent httpd (nginx?) config and supply the config myself in `finish_rootfs_build` hook or via Dockerfile. Prefer the former if possible as it saves you some docker image layers. You could also do a manual install in a interactive build container and just copy the generated webapp-config files. Google is probably faster though.

As you still seem to struggle a bit with the basic concept I'd recommend reading the `How does it work?` section again. [package.provided](https://wiki.gentoo.org/wiki//etc/portage/profile/package.provided) is another important piece in the puzzle to understand. Then just remember this for the hooks:

* `configure_bob` - you can run emerge manually and it will run in the normal `/` context, packages you install won't show up in the rootfs.tar but everything just works(tm) and you also get a free binary package as a bonus

* `configure_rootfs_build` - when emerge is executed to handle `PACKAGES`, the `ROOT` env is set to `/emerge-root`, except for the portage tree and some gcc related tools emerge doesn't see stuff like python which is installed under `/`, depending on the ebuild/upstream build quality of the package this can cause all sorts of errors. For example, if you extend from the java image and try to install a package that requires java for installation, this won't work because `package.provided` from the java build container tells emerge that java is already there, but in reality there is no java at `/emerge-root`. It's in a previous layer. Those parts of the installation process need to be run via Dockerfile in the last build phase, but ofcourse at that point there is no `emerge` you could execute. The right path depends on the package but generally it comes down to one of these:

1. build error as expected stuff in the path does not exist => generate binary package in previous hook
2. parts of the build process (usually post install) require the full final image context, ruby gem installs for example => run via Dockerfile in the last build phase

* `finish_rootfs_build` - shouldn't really run emerge here except for uninstalling packages that were only needed at build time in the `configure_rootfs_build` hook

**Comment by soredake** [comment]
Thanks. Seems i can't avoid many errors because of webapp.eclass, i think it is easier to install it manually instead of using the portage.
